- hosts: localhost
  become: yes
  tasks:
        - name: Build an image and push it to a docker repository
          community.docker.docker_image:
              build:
                  path: "/home/edureka/Desktop"
              name: docker.io/purushottam87/xyztechnologies
              #tag: test
              push: true
              source: build
          register: out
        - debug:
              var: out  
        - name: start a container
          community.docker.docker_container:
             name: xyz-technologies-application
             image: docker.io/purushottam87/xyztechnologies
             state: started
             ports:
                 - 3080:8080
          register: out
        - debug:
              var: out
        - name: Deploy to kubernetes
          command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/edureka/Desktop/project2-required-files/deployment.yml" 
          #command: "kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f /home/edureka/Desktop/project2-required-files/service.yml"    
          register: out
        - debug:
              var: out
