kind: Deployment
apiVersion: apps/v1
metadata:
    name: xyztechnologies-deployment
spec:
    replicas: 2
    minReadySeconds: 45
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 2
    selector:
        matchLabels:
            app: xyz-technologies-app
    template:
        metadata:
            labels:
                app: xyz-technologies-app
        spec:
            containers:
                - image: purushottam87/xyztechnologies 
                  name:  xyz-technologies-con-app
